version: "3.8"
services:
  ioc:
    image: lnls/${IOC_REPO}:${COMMIT}-${BASE_VERSION}-${DEBIAN_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        org.opencontainers.image.revision: ${COMMIT}
        org.opencontainers.image.source: https://github.com/${IOC_GROUP}/${IOC_REPO}.git
      args:
        BASE_VERSION: ${BASE_VERSION}
        COMMIT: ${COMMIT}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        IOC_GROUP: ${IOC_GROUP}
        IOC_REPO: ${IOC_REPO}
        SYNAPPS_VERSION: ${SYNAPPS_VERSION}